/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */


plugins {
    id("buildlogic.java-application-conventions")
}


application {
    // Define the main class for the application.
    mainClass = "org.jpc.emulator.App"
}

dependencies {
    implementation(project(":emulator-lib"))
}

// Add emulator-lib's resources to this JAR
tasks.jar {
    manifest {
        attributes["Main-Class"] = application.mainClass.get()
    }
    // Make sure the emulator-lib is compiled first
    dependsOn(":emulator-lib:classes")

    // Merge emulator-lib's classes into emulator.jar
    from(project(":emulator-lib").the<JavaPluginExtension>().sourceSets["main"].output)

    // Make sure emulator-lib has processed its resources first
    dependsOn(":emulator-lib:processResources")

    // Copy the output of emulator-lib's main resources into our jar.
    // By default, Gradle places those processed resources under build/resources/main.
    from("${project(":emulator-lib").buildDir}/resources/main") {
        // If you want them in a subfolder inside the JAR, say "emulator-lib/", do:
        // into("emulator-lib")
        include("**/*")
        // Put them under a folder named "resources" in the jar:
        into("resources")
    }
}
